name: Build
on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '!production'   # excludes master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run test
      env:
        CI: true
